### ISSUE TITLE
ClassNotFoundException - IOUtils

### ISSUE THREAD

**Issue by wedgef5** [sshtools/maverick-synergy#72]
I'm trying to use the 3.0.9 client jar, and I am getting...

Exception in thread "main" java.lang.NoClassDefFoundError: com/sshtools/common/util/IOUtils
	at com.sshtools.common.publickey.SshKeyUtils.getPrivateKey(SshKeyUtils.java:80)
	at com.sshtools.client.SshClient.<init>(SshClient.java:80)
	at com.sshtools.client.SshClient.<init>(SshClient.java:76)

I can't find IOUtils in any of the jars in the 3.0.9 release.

**Comment by ludup** [comment]
IOUtils is in the maverick-utils module. Without knowing your classpath set up it's impossible to advise on your issue.
