### ISSUE TITLE
Getting runtime error

### ISSUE THREAD

**Issue by vyasakshay** [sshtools/maverick-synergy#74]
Getting this error while running. It seams you have compiled it with JDK higher than 8. When running the jar with version 8 throws this error.
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;|

at com.sshtools.synergy.nio.SocketConnection.processWriteEvent(SocketConnection.java:358)|

at com.sshtools.synergy.nio.SshEngine$SocketReadWriteTask.doTask(SshEngine.java:979)|

at com.sshtools.common.ssh.ConnectionAwareTask.run(ConnectionAwareTask.java:45)|

at com.sshtools.common.ssh.ExecutorOperationSupport$OperationTask.executeAllTasks(ExecutorOperationSupport.java:127)|

at com.sshtools.common.ssh.ExecutorOperationSupport$OperationTask.run(ExecutorOperationSupport.java:84)|

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)|

at java.util.concurrent.FutureTask.run(FutureTask.java:266)|

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)|

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)|

at java.lang.Thread.run(Thread.java:750)|

**Comment by ludup** [comment]
What version?

**Comment by vyasakshay** [comment]
The latest version 3.0.10

**Comment by vyasakshay** [comment]
Not getting the error in version 3.0.9

**Comment by ludup** [comment]
That's strange because the build log for that build shows it being built with Java 8. 

We have recently moved to a minimum of Java 11 for the 3.1.0 branch, I can only think that somewhere it got built with this, although Maven Central generally does not allow overwriting of artifacts so how that could have happened, given the build log I'm seeing of 3.0.10

As I can't replace 3.0.10 I will have to create a separate branch 3.0.10 and bump the version to recompile it. Since this is not trivial because develop as already moved onto 3.1.0 it will take a little while.

**Comment by vyasakshay** [comment]
I can work with version 3.0.9 for now. Please do share the build once you could take a branch and rebuild it. We might need other bug fixes included in version 3.0.10
